[tool.poetry]
name = "cnn-image-recog"
version = "0.1.0"
description = "CNN Image Recognition Experiments"
authors = ["amit <bakhru@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "*"
colorlog = "*"
imageai = "*"
pandas = "*"
torchvision = "*"
keras = "*"
jupyterlab = "*"
gradio = "*"
easyocr = "*"
dlib = "*"
safety = "*"
bandit = "*"
coverage = "*"
pytest = "*"
requests = "*"
pillow = "*"
opencv-python = "*"
matplotlib = "*"
parameterized = "*"
tensorflow = "^2.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
