[tool.poetry]
name = "cnn-image-recog"
version = "0.1.0"
description = "CNN Image Recognition Experiments"
authors = ["amit <bakhru@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
colorlog = "^6.8.2"
imageai = "^3.0.3"
pandas = "^2.2.1"
tensorflow = "^2.16.1"
torchvision = "^0.17.2"
keras = "^3.1.1"
jupyterlab = "^4.1.5"
gradio = "^4.24.0"
easyocr = "^1.7.1"
dlib = "^19.24.2"
safety = "^3.1.0"
bandit = "^1.7.8"
coverage = "^7.4.4"
pytest = "^8.1.1"
requests = "^2.31.0"
pillow = "^10.2.0"
opencv-python = "^4.9.0.80"
matplotlib = "^3.8.3"
parameterized = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
